services:
  sync-db:
    image: docker.io/library/mysql:5.7
    volumes:
      - sync_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306"
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: random
      MYSQL_DATABASE: syncstorage
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  tokenserver-db:
    image: docker.io/library/mysql:5.7
    volumes:
      - tokenserver_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306"
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: random
      MYSQL_DATABASE: tokenserver
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  mock-fxa-server:
    image: app:build
    restart: "no"
    entrypoint: "sh scripts/start_mock_fxa_server.sh"
    environment:
      MOCK_FXA_SERVER_HOST: 0.0.0.0
      MOCK_FXA_SERVER_PORT: 6000

  syncserver:
    image: ${SYNCSTORAGE_RS_IMAGE:-syncstorage-rs:latest}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - sync-db
      - tokenserver-db
    environment:
      SYNC_HOST: 0.0.0.0
      SYNC_MASTER_SECRET: secret0
      SYNC_SYNCSTORAGE__DATABASE_URL: mysql://test:test@sync-db:3306/syncstorage
      SYNC_TOKENSERVER__DATABASE_URL: mysql://test:test@tokenserver-db:3306/tokenserver
      SYNC_TOKENSERVER__RUN_MIGRATIONS: "true"

volumes:
  sync_db_data:
  tokenserver_db_data: